### ISSUE TITLE
Remove folders which don't contain config files

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-config-tree#2]
Just remove folders from the tree, when the folder doesn't contain *.config files and therefore e.g. the folder "Splashes" would be removed from the tree.

http://our.umbraco.org/projects/developer-tools/config-tree/using-config-tree/56963-Exclude-the-folder-Splashes

**Comment by NikRimington** [comment]
Hi lee, I'm guessing this issue never got resolved?
The error is being caused when the code tries to find the path to the folder, basically it isn't appending a \ to it.
' System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\code\SS\Development branch\SS\configsplashes'. '

The path should read  config\splashes.

**Comment by leekelleher** [comment]
Thanks @NikRimington - although I think this is a different issue.  I've never known the Config Tree to throw an exception for this.  The file/folder listing is actually done by Umbraco core itself, (Config Tree references Umbraco's `FileSystemTree`, which handles that side of it).

Which version of Umbraco are you using?

**Comment by NikRimington** [comment]
Hi @leekelleher , I'm using version 7.2.6. The issue occurs when you click to browse the folder it's showing in the tree itself. 

This is the full error with the stack trace which was what made me think it was related to this:

````
    Failed to retrieve data for child nodes undefined

Could not find a part of the path 'E:\code\SS\Development branch\SS\configsplashes'.

EXCEPTION DETAILS:

System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\code\SS\Development branch\SS\configsplashes'.
STACKTRACE:

at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetDirectories(String searchPattern, SearchOption searchOption)
   at System.IO.DirectoryInfo.GetDirectories()
   at umbraco.cms.presentation.Trees.FileSystemTree.Render(XmlTree& tree)
   at Our.Umbraco.Tree.Config.LoadConfigFiles.Render(XmlTree& tree)
   at Umbraco.Web.Trees.ApplicationTreeExtensions.TryGetXmlTree(ApplicationTree appTree, String id, FormDataCollection formCollection)
   at Umbraco.Web.Trees.ApplicationTreeExtensions.TryLoadFromLegacyTree(ApplicationTree appTree, String id, FormDataCollection formCollection, UrlHelper urlHelper, String currentSection)
   at Umbraco.Web.Trees.LegacyTreeController.GetTreeNodes(String id, FormDataCollection queryStrings)
   at Umbraco.Web.Trees.TreeControllerBase.GetNodes(String id, FormDataCollection queryStrings)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass13.<GetExecutor>b__c(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.<>c__DisplayClass5.<ExecuteAsync>b__4()
   at System.Threading.Tasks.TaskHelpers.RunSynchronously[TResult](Func`1 func, CancellationToken cancellationToken)
````
